### ISSUE TITLE
Issue with horizontal scroll

### ISSUE THREAD

**Issue by SumraYasmin** [abinoam/col_resizable-rails#1] opened 2019-05-21 09:15 UTC
I have a table with horizontal scroll. which does not appear in right way after using this gem.

**Comment by SumraYasmin** [comment] 2019-05-21 10:57
I can fix the view issue by overriding ```table-layout: fixed; ``` but resizing does not work with horizontal scroll.

**Comment by SumraYasmin** [comment] 2019-05-21 10:58
@abinoam kindly have a look.

Any help will be appreciated.
Thanks.

**Comment by abinoam** [comment] 2019-05-22 00:08
What is your Ruby and Rails versions?

It's been at least 2 years since I've done this gem for a project that I was using at that time.
Since then, we have migrated our assets from sprockets to webpacker like in:
* https://www.calleerlandsson.com/replacing-sprockets-with-webpacker-for-javascript-in-rails-5-2/
* https://samuelmullen.com/articles/embracing-change-rails51-adopts-yarn-webpack-and-the-js-ecosystem/

I would recommend you to do the same (if possible).

I have to be sincere with you, I will not have time to have a look at this till sunday.
Even if I've had time, it would be really hard for me to debug this without a fragment of code that i could reproduce the issue and possible some screenshots.

So, if you don't solve this until sunday, please post some code that I can reproduce the issue in my machine and I can see if I could help. Although I think this is more related to the js library itself than with the packed gem.

If you solve it, please post the answer here so others can benefit from that. 👍

**Comment by abinoam** [comment] 2019-06-04 10:12
Closing this issue as it is stall. Feel free to reopen it at any time if you find it necessary.

**Closed as completed by abinoam** 2019-06-04 10:12 UTC
